:doc:`S3 <../../../s3>` / Client / exceptions / BucketAlreadyOwnedByYou

***********************
BucketAlreadyOwnedByYou
***********************



.. py:class:: S3.Client.exceptions.BucketAlreadyOwnedByYou

  
  

  The bucket you tried to create already exists, and you own it. Amazon S3 returns this error in all Amazon Web Services Regions except in the North Virginia Region. For legacy compatibility, if you re-create an existing bucket that you already own in the North Virginia Region, Amazon S3 returns 200 OK and resets the bucket access control lists (ACLs).

  
  
  **Example**

  ::

    try:
      ...
    except client.exceptions.BucketAlreadyOwnedByYou as e:
      print(e.response)

  



  .. py:attribute:: response

    
    The parsed error response. All exceptions have a top level ``Error`` key that provides normalized access to common exception atrributes. All other keys are specific to this service or exception class.
    

  
    **Syntax**

    
    ::

      {}
      
    **Structure**

    

    - *(dict) --* 

      The bucket you tried to create already exists, and you own it. Amazon S3 returns this error in all Amazon Web Services Regions except in the North Virginia Region. For legacy compatibility, if you re-create an existing bucket that you already own in the North Virginia Region, Amazon S3 returns 200 OK and resets the bucket access control lists (ACLs).

      
      

      - **Error** *(dict) --* Normalized access to common exception attributes.
        

        - **Code** *(string) --* An identifier specifying the exception type.
        

        - **Message** *(string) --* A descriptive message explaining why the exception occured.
    
  